Algoritmo "EXERCICIO 36,"
// Disciplina   : [Lógica de Programação e Java Script]
// Professor   : Jailson
// Descrição   : Escreva um algoritmo que leia as idades de 2 homens e de 2 mulheres (considere que as idadesdos homens serão sempre diferentes entre si, bem como as das mulheres). Calcule e escreva a somadas idades do homem mais velho com a mulher mais nova, e o produto das idades do homem mnovo com a mulher mais velha.
// Data atual  : 16/09/2022
Var
// Seção de Declarações das variáveis 
 mulher1:real
 mulher2:real
 homem1:real
 homem2:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite a idade da primeira mulher: ")
leia(mulher1)
escreval("Digite a idade da segunda mulher: ")
leia(mulher2)
escreval("Digite a idade do primeiro homem: ")
leia(homem1)
escreval("Digite a idade do segundo homem: ")
leia(homem2)
 //Calcule e escreva a soma das idades do homem mais velho com a mulher mais nova

 // produto das idades do homem mais novo com a mulher mais velha.
Fimalgoritmo