Algoritmo "EXERCICIO 27 , positivo negativo zero"
// Disciplina   : [Lógica de Programação e Java Script]
// Professor   : Jailson
// Descrição   :Ler um valor e escrever se é positivo, negativo ou zero.
// Autor(a)    : Núbia
// Data atual  : 16/09/2022
Var
// Seção de Declarações das variáveis 
numero:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número qualquer: ")
leia(numero)
se numero < 0 entao
escreval("é um numero negativo)
senao
se numero > 0 entao
escreval("é um numero positivo")
senao
escreva("Igual a zero")
fimse

Fimalgoritmo
