Algoritmo "EXERCICIO 31 , lados de um triangulo "
// Disciplina   : [Lógica de Programação E Java Script]
// Professor   : Jailson
// Descrição   : Ler 3 valores (A, B e C) representando as medidas dos lados de um triângulo e escrever se formam ou não um triângulo. OBS: para formar um triângulo, o valor de cada lado deve ser menor que a soma dos outros 2 lados.
// Autor(a)    : Núbia
// Data atual  : 16/09/2022
Var
// Seção de Declarações das variáveis 
lado1:inteiro
lado2:inteiro
lado3:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
//para formar um triângulo, o valor de cada lado deve ser menor que a soma
//dos outros 2 lados.
escreval("Lado 1: ")

leia(lado1)
escreval("Lado 2: ")
leia(lado2)
escreval("Lado 3 :")
leia(lado3)
se ( lado1 < lado2 + lado3)entao
se ( lado2 < lado1 + lado 3)entao
se ( lado3 < lado1 + lado2)entao
escreval ("O triangulo existe.")
senao
escreval (" O triangulo nao existe. ")
fimse





Fimalgoritmo