Algoritmo "Exercicio14(desvio)"
// Disciplina   : [Lógica de Programação e java script]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Ler um valor e escrever a mensagem É MAIOR QUE 10! se o valor lido for maior que 10, caso contrário escrever NÃO É MAIOR QUE 10!
// Autor(a)    : Núbia
// Data atual  : 09/09/2022
Var
// Seção de Declarações das variáveis 
  numero:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um numero : ")
   Leia(numero)
   se numero>10 entao
   Escreval("O numero é maior que 10")
   fimse
   se numero<10 entao
   Escreval("O numero é menor que 10")
   fimse
Fimalgoritmo