Algoritmo "EXERCICIO 34, "
// Disciplina   : [Lógica de Programação e Java script]
// Professor   :Jailson
// Descrição   :Faça um teste de mesa e complete o quadro a seguir para os seguintes valores:
// Autor(a)    : Núbia
// Data atual  : 16/09/2022
Var
// Seção de Declarações das variáveis 
 x,y,z:real
 resposta:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Escreva um número")
leia(x)
escreval("Escreva outro numero")
leia(y)
resposta<-(x+y) + 5
se z<=0 entao
escreval("A resposta é A" )
senao
se z>0 ate 100 entao
escreval("A resposta é B" )
senao
escreval("A resposta é C" )
fimse
fimse





Fimalgoritmo
