Algoritmo "exercicio15(desvio)"
// Disciplina   : [Lógica de Programação e java script]
// Professor   : Jailson
// Descrição   : Ler um valor e escrever se é positivo ou negativo (considere o valor zero como positivo).
// Autor(a)    : Núbia
// Data atual  : 09/09/2022
Var
// Seção de Declarações das variáveis 
  valor:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Digite um valor : ")
   Leia(valor)
   se valor<0 entao
   Escreval("É um valor negativo")
   fimse

   se valor>1 entao
   Escreval("É um valor positivo")
  fimse
Fimalgoritmo