Algoritmo "EXERCICIO 38,Código de usuario"
// Disciplina   : [Lógica de Programação e Java Script]
// Professor   : Jailson
// Descrição   :Faça um algoritmo para ler um número que é um código de usuário. Caso este código sejadiferente de um código armazenado internamente no algoritmo (igual a 1234) deve ser apresentada amensagem ‘Usuário inválido!’. Caso o Código seja correto, deve ser lido outro valor que é a senha. Seesta senha estiver incorreta (a certa é 9999) deve ser mostrada a mensagem ‘senha incorreta’. Caso a senha esteja correta, deve ser mostrada a mensagem ‘Acesso permitido’.
// Autor(a)    : Núbia
// Data atual  : 16/09/2022
Var
// Seção de Declarações das variáveis 
codigo:inteiro
senha:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o código do usuário: ")
leia(codigo)
//login correto:1234
se (codigo<>1234) entao
escreval("Usuário inválido")
senao
escreval("Digite a Senha: ")
leia(senha)
//senha correta:9999
se (senha<>9999) entao
escreval ("Senha incorreta!")
senao
escreval ("Acesso Permitido!")
fimse
fimse

Fimalgoritmo