Algoritmo "Exercicio18,pode ou não votar "
// Disciplina   : [Lógica de Programação e java script]
// Professor   : Jailson
// Descrição   : Ler o ano atual e o ano de nascimento de uma pessoa. Escrever uma mensagem que diga se ela
//poderá ou não votar este ano (não é necessário considerar o mês em que a pessoa nasceu).
// Autor(a)    : Núbia
// Data atual  : 12/09/2022
Var
// Seção de Declarações das variáveis

 anoatual:inteiro
 anonascimento:inteiro
 idade:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("informe o ano atual ")
leia(anoatual)
escreval("informe o ano que voc~e nasceu")
leia(anonascimento)
 se idade=16  entao
escreval("pode votar")
senao
escreval("nao pode votar")
fimse
Fimalgoritmo