Algoritmo "EXERCICIO 29 , soma dos dois maiores"
// Disciplina   : [Lógica de Programação e Java Script]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Ler 3 valores (considere que não serão informados valores iguais) e escrever a soma dos 2 maiores.
// Autor(a)    : Núbia
// Data atual  : 16/09/2022
Var
// Seção de Declarações das variáveis 
 valor1:inteiro
 valor2:inteiro
 valor3:inteiro
 total:inteiro
 total1:inteiro
 total2:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("digite um valor")
 leia (valor1)
 escreval ("digite um valor que deve ser diferente do valor 1")
 leia (valor2)
 escreval ("digite um valor que deve ser diferente do valor 1 ou 2")
 leia (valor3)
 se (valor3<valor1) && (valor1<valor2> entao
 total<-valor1+valor2
 fimse
 se (valor2<valor1) && (valor1<valor3> entao
 total1<-valor1+valor3
 senão
 total2<-valor2+valor3
 fimse

 
























Fimalgoritmo