Algoritmo "EXERCICIO 33, ler valores"
// Disciplina   : [Lógica de Programação e Java script]
// Professor   : Jailson
// Descrição   : Ler dois valores e imprimir uma das três mensagens a seguir: Números iguais’, caso os números sejam iguais‘Primeiro é maior’, caso o primeiro seja maior que o segundo;‘Segundo maior’, caso o segundo seja maior que o primeiro
// Autor(a)    : Núbia
// Data atual  : 16/09/2022
Var
// Seção de Declarações das variáveis 
numero1:inteiro
numero2:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o primeiro numero")
leia(numero1)
escreval("Digite o segundo numero")
leia(numero2)
se numero1=numero2 entao
escreval("Os números são iguais")
senao
se numero1>numero2 entao
escreval("O primeiro número é maior")
senao
escreval("O segundo número e maior")
fimse
fimse

Fimalgoritmo